/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AprovarTokenRouteImport } from './routes/aprovar.$token'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedPerdasRouteImport } from './routes/_authenticated/perdas'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContarRouteImport } from './routes/_authenticated/contar'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedInventariosIndexRouteImport } from './routes/_authenticated/inventarios.index'
import { Route as AuthenticatedInventariosIdRouteImport } from './routes/_authenticated/inventarios.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovarTokenRoute = AprovarTokenRouteImport.update({
  id: '/aprovar/$token',
  path: '/aprovar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerdasRoute = AuthenticatedPerdasRouteImport.update({
  id: '/perdas',
  path: '/perdas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContarRoute = AuthenticatedContarRouteImport.update({
  id: '/contar',
  path: '/contar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventariosIndexRoute =
  AuthenticatedInventariosIndexRouteImport.update({
    id: '/inventarios/',
    path: '/inventarios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventariosIdRoute =
  AuthenticatedInventariosIdRouteImport.update({
    id: '/inventarios/$id',
    path: '/inventarios/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contar': typeof AuthenticatedContarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/perdas': typeof AuthenticatedPerdasRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/aprovar/$token': typeof AprovarTokenRoute
  '/inventarios/$id': typeof AuthenticatedInventariosIdRoute
  '/inventarios/': typeof AuthenticatedInventariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contar': typeof AuthenticatedContarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/perdas': typeof AuthenticatedPerdasRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/aprovar/$token': typeof AprovarTokenRoute
  '/inventarios/$id': typeof AuthenticatedInventariosIdRoute
  '/inventarios': typeof AuthenticatedInventariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contar': typeof AuthenticatedContarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/perdas': typeof AuthenticatedPerdasRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/aprovar/$token': typeof AprovarTokenRoute
  '/_authenticated/inventarios/$id': typeof AuthenticatedInventariosIdRoute
  '/_authenticated/inventarios/': typeof AuthenticatedInventariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/contar'
    | '/dashboard'
    | '/inicio'
    | '/logs'
    | '/perdas'
    | '/ranking'
    | '/relatorios'
    | '/usuarios'
    | '/aprovar/$token'
    | '/inventarios/$id'
    | '/inventarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/contar'
    | '/dashboard'
    | '/inicio'
    | '/logs'
    | '/perdas'
    | '/ranking'
    | '/relatorios'
    | '/usuarios'
    | '/aprovar/$token'
    | '/inventarios/$id'
    | '/inventarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contar'
    | '/_authenticated/dashboard'
    | '/_authenticated/inicio'
    | '/_authenticated/logs'
    | '/_authenticated/perdas'
    | '/_authenticated/ranking'
    | '/_authenticated/relatorios'
    | '/_authenticated/usuarios'
    | '/aprovar/$token'
    | '/_authenticated/inventarios/$id'
    | '/_authenticated/inventarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AprovarTokenRoute: typeof AprovarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovar/$token': {
      id: '/aprovar/$token'
      path: '/aprovar/$token'
      fullPath: '/aprovar/$token'
      preLoaderRoute: typeof AprovarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perdas': {
      id: '/_authenticated/perdas'
      path: '/perdas'
      fullPath: '/perdas'
      preLoaderRoute: typeof AuthenticatedPerdasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contar': {
      id: '/_authenticated/contar'
      path: '/contar'
      fullPath: '/contar'
      preLoaderRoute: typeof AuthenticatedContarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventarios/': {
      id: '/_authenticated/inventarios/'
      path: '/inventarios'
      fullPath: '/inventarios/'
      preLoaderRoute: typeof AuthenticatedInventariosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventarios/$id': {
      id: '/_authenticated/inventarios/$id'
      path: '/inventarios/$id'
      fullPath: '/inventarios/$id'
      preLoaderRoute: typeof AuthenticatedInventariosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContarRoute: typeof AuthenticatedContarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedPerdasRoute: typeof AuthenticatedPerdasRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedInventariosIdRoute: typeof AuthenticatedInventariosIdRoute
  AuthenticatedInventariosIndexRoute: typeof AuthenticatedInventariosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContarRoute: AuthenticatedContarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedPerdasRoute: AuthenticatedPerdasRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedInventariosIdRoute: AuthenticatedInventariosIdRoute,
  AuthenticatedInventariosIndexRoute: AuthenticatedInventariosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AprovarTokenRoute: AprovarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
