/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedContarRouteImport } from './routes/_authenticated/contar'
import { Route as AuthenticatedInventariosIndexRouteImport } from './routes/_authenticated/inventarios.index'
import { Route as AuthenticatedInventariosIdRouteImport } from './routes/_authenticated/inventarios.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContarRoute = AuthenticatedContarRouteImport.update({
  id: '/contar',
  path: '/contar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventariosIndexRoute =
  AuthenticatedInventariosIndexRouteImport.update({
    id: '/inventarios/',
    path: '/inventarios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventariosIdRoute =
  AuthenticatedInventariosIdRouteImport.update({
    id: '/inventarios/$id',
    path: '/inventarios/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contar': typeof AuthenticatedContarRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/inventarios/$id': typeof AuthenticatedInventariosIdRoute
  '/inventarios/': typeof AuthenticatedInventariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contar': typeof AuthenticatedContarRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/inventarios/$id': typeof AuthenticatedInventariosIdRoute
  '/inventarios': typeof AuthenticatedInventariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contar': typeof AuthenticatedContarRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/inventarios/$id': typeof AuthenticatedInventariosIdRoute
  '/_authenticated/inventarios/': typeof AuthenticatedInventariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contar'
    | '/inicio'
    | '/inventarios/$id'
    | '/inventarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contar'
    | '/inicio'
    | '/inventarios/$id'
    | '/inventarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contar'
    | '/_authenticated/inicio'
    | '/_authenticated/inventarios/$id'
    | '/_authenticated/inventarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contar': {
      id: '/_authenticated/contar'
      path: '/contar'
      fullPath: '/contar'
      preLoaderRoute: typeof AuthenticatedContarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventarios/': {
      id: '/_authenticated/inventarios/'
      path: '/inventarios'
      fullPath: '/inventarios/'
      preLoaderRoute: typeof AuthenticatedInventariosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventarios/$id': {
      id: '/_authenticated/inventarios/$id'
      path: '/inventarios/$id'
      fullPath: '/inventarios/$id'
      preLoaderRoute: typeof AuthenticatedInventariosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContarRoute: typeof AuthenticatedContarRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedInventariosIdRoute: typeof AuthenticatedInventariosIdRoute
  AuthenticatedInventariosIndexRoute: typeof AuthenticatedInventariosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContarRoute: AuthenticatedContarRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedInventariosIdRoute: AuthenticatedInventariosIdRoute,
  AuthenticatedInventariosIndexRoute: AuthenticatedInventariosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
